### ISSUE TITLE
From address field case sensitivity

### ISSUE THREAD

**Issue by plasmacorral** [svanas/migratooor#2]
When adding an address with mixed case letters (like copy/paste from etherscan) the assets associated with a "from" address are unable to be found in scan.  
![Screen Shot 2022-01-27 at 12 16 59 PM](https://user-images.githubusercontent.com/32695229/151409746-78fc7f0c-10a7-451d-8d73-8291f53d626a.png)

Once I replaced the lower case with upper, assets were located.  Using mixed case supports checksums on an addresses: https://support.mycrypto.com/general-knowledge/ethereum-blockchain/ethereum-address-has-uppercase-and-lowercase-letters
![Screen Shot 2022-01-27 at 12 17 21 PM](https://user-images.githubusercontent.com/32695229/151409795-a690d1af-476a-4921-bcd4-f1957193b6a8.png)
/

**Comment by svanas** [comment]
Fixed in https://github.com/svanas/delphereum/commit/342c712ff6f92cd85bedd6251fb658ee9dbe666e

**Comment by plasmacorral** [comment]
The comment here " allow for addresses starting with 0X (not with 0x)"  indicates that I was not clear in describing the problem.  

When I used the address as copied from MetaMask or Etherscan, assets are not able to be found.  When I replaced ALL lower case letters with their capital equivalent in version 0.0.3, only then would the app locate and present assets.  

In version 0.0.5 I can no longer find assets in mixed case OR after replacing all lower case with caps. The fix has actually made the app less usable as it cannot find any assets at all, even after I substitute out the lower case letters.

**Comment by svanas** [comment]
> When I used the address as copied from MetaMask or Etherscan, assets are not able to be found.

This is because [there aren't any tokens to be found](https://etherscan.io/address/0x43A32EcD8B7B1f4748A7f46805A671AeA32046e1). We scan the [Uniswap Labs List](https://tokenlists.org/token-list?url=https://gateway.ipfs.io/ipns/tokens.uniswap.org) (92 tokens) and the [CoinGecko tokenlist](https://tokenlists.org/token-list?url=https://tokens.coingecko.com/uniswap/all.json) (4917 tokens).

> When I replaced ALL lower case letters with their capital equivalent in version 0.0.3, only then would the app locate and present assets.

In this scenario, the app would resolve the uppercase address to [0x0](https://etherscan.io/address/0x0000000000000000000000000000000000000000), and then scan for tokens in the [0x0](https://etherscan.io/address/0x0000000000000000000000000000000000000000) address. This is a bug, and this has been fixed.

**Comment by plasmacorral** [comment]
Thank you for the patch and response.

While the address under test does lack assets on Ethereum mainnet, there are several testnet assets present. Using the drop-down to select Kovan or Rinkeby with "select all tokens" checked and tapping "scan", does not present the testnet assets in the app.
 https://blockscan.com/address/0x43A32EcD8B7B1f4748A7f46805A671AeA32046e1

**Comment by svanas** [comment]
Unfortunately, there are only so many tokens on Ethereum testnets we know about. The [Uniswap tokenlist](https://tokenlists.org/token-list?url=https://gateway.ipfs.io/ipns/tokens.uniswap.org) includes...
* 3 tokens on Ropsten
* 4 tokens on Rinkeby
* 2 tokens on Goerli
* 4 tokens on Kovan

I'm open to other tokenlists for Ropsten/Rinkeby/Goerli/Kovan, but so far I haven't found any.
